edition = "2018"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "crate"
imports_layout = "vertical"
match_block_trailing_comma = true
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
trailing_comma = "vertical"
wrap_comments = true