name: Build Release
on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --release
      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: chunky-bits-release
          path: target/release/chunky-bits