name: Compile
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: rustup component add rustfmt --toolchain nightly
      - run: cargo +nightly fmt
      - run: git status | grep clean